live_config_reload = true

[font]
size = 14.0

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[window]
decorations = "None"
dynamic_padding = false
opacity = 0.85

[window.padding]
x = 18
y = 14

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullScreen" }]
